spring.application.name=anki-telegram-bot
bot.token=${BOT_TOKEN}
bot.username=${BOT_USERNAME}
bot.allowed.chat.id=${ALLOWED_CHAT_ID}
gemini.url=${GEMINI_URL:https://generativelanguage.googleapis.com/v1beta/models/}
gemini.model=${GEMINI_MODEL:gemini-flash-lite-latest}
gemini.api.key=${GEMINI_API_KEY}
anki.export.path=anki_cards.txt
anki.connect.url=http://localhost:8765
anki.connect.jp=${DECK_NAME_JP}
anki.connect.eng=${DECK_NAME_ENG}
anki.connect.model=${ANKI_MODEL_NAME}
