spring.application.name=anki-telegram-bot
bot.token=${BOT_TOKEN}
bot.username=${BOT_USERNAME}
bot.allowed.chat.id=${ALLOWED_CHAT_ID}
gemini.url=${GEMINI_URL:https://generativelanguage.googleapis.com/v1beta/models/}
gemini.model=${GEMINI_MODEL:gemini-flash-lite-latest}
gemini.api.key=${GEMINI_API_KEY}
anki.export.path=anki_cards.txt
logging.level.org.telegram.telegrambots.updatesreceivers=WARN
logging.file.name=${user.home}/.anki-tg-bot/bot.log
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=7
anki.connect.url=http://localhost:8765
anki.connect.jp=${DECK_NAME_JP}
anki.connect.eng=${DECK_NAME_ENG}
anki.connect.model=${ANKI_MODEL_NAME}
bot.settings.path=${BOT_SETTINGS_PATH:}
